name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Angular
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production 
        base_href: /simple-app-automated-testing-sample/  
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/project
