name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Angular
      uses: ./
      with:
        build_configuration: production 
        base_href: ./
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/project
