name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: janynnegomes/simple-app-automated-testing-sample
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /simple-app-automated-testing-sample/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: docs # The branch the action should deploy to.
        angular_dist_build_folder: dist/project # The folder where your project is supposed to be after running ng build by the action.
