# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Unit Test
      run: npm run test
   
    - name: UI Automated Test
      run: npm run e2e

    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.0
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        base_href: https://janynnegomes.github.io/simple-app-automated-testing-sample
        angular_project_dir: ./
        build_configuration:  production
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/project
        skip_failure: false
        
    - name: Angular coverage badges
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        # Token for the repository. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.ACCESS_TOKEN }}
