# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
   runs-on: ubuntu-18.04

   steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
       node-version: 12.8
       
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build -- --prod
      
    - name: Test
      run: npm test
      
    - name: E2E
      run: npm run e2e 

    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.0
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        base_href: https://janynnegomes.github.io/simple-app-automated-testing-sample
        angular_project_dir: ./
        build_configuration:  production
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/project
        skip_failure: false
